name: CI

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest
      - name: Run tests
        run: pytest -q

  publish-to-pypi:
    name: Publish to PyPI
    if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/v')
    needs:
    - test
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/git-rescue/
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Build distributions
      run: |
        python -m pip install --upgrade pip build
        python -m build
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
